restructure docs in opf format
aicoe-aiops/time-series pull request #46
Opened 2021-08-16 19:54 UTC by Shreyanand

## Related Issues and Dependencies

https://github.com/operate-first/operate-first.github.io/issues/275

## This introduces a breaking change

- [ ] Yes
- [X] No

## Description

In this PR, we restructure the project docs to match the standard opf format.

2021-08-16 19:54 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **shreyanand** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aicoe-aiops%2Ftime-series).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/aicoe-aiops/time-series/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["shreyanand"]} -->

2021-08-16 20:54 UTC, aakankshaduggal requested changes
Overall /lgtm
Just minor comments :+1:

2021-08-16 20:54 UTC, aakankshaduggal commented on docs/contribute.md
> +1. If you have an notebooks to contribute towards this project, please [open an issue](https://github.com/aicoe-aiops/time-series/issues) on project's [Github Repository](https://github.com/aicoe-aio
nit - an -> any

2021-08-16 20:54 UTC, aakankshaduggal commented on docs/content.md
> +Check out the [overview](../) page which goes over the motivation of the project.
I tried this link from your fork, it's giving me an error. Should we just point to the README directly here?

2021-08-17 13:26 UTC, oindrillac reviewed
/lgtm

2021-08-20 20:01 UTC, sesheta commented
New changes are detected. LGTM label has been removed.

2021-08-20 20:02 UTC, Shreyanand commented on docs/contribute.md
> +1. If you have an notebooks to contribute towards this project, please [open an issue](https://github.com/aicoe-aiops/time-series/issues) on project's [Github Repository](https://github.com/aicoe-aio
+1

2021-08-20 20:05 UTC, Shreyanand commented on docs/content.md
> +Check out the [overview](../) page which goes over the motivation of the project.
I had tried pointing it to the README directly but that messes up links on the website. If we use the absolute link, then the links on the README page won't be accessible, so I thought the website should get precedence over the repository...

2021-08-20 20:06 UTC, aakankshaduggal commented
Sounds good @Shreyanand /lgtm

2021-08-25 13:26 UTC, oindrillac approved these changes
/lgtm
/approve

2021-08-25 13:27 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aicoe-aiops/time-series/pull/46#pullrequestreview-738351629" title="Approved">oindrillac</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **shreyanand** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aicoe-aiops%2Ftime-series).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/aicoe-aiops/time-series/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["shreyanand"]} -->

2021-08-25 14:07 UTC, MichaelClifford commented
/approve

2021-08-25 14:07 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aicoe-aiops/time-series/pull/46#issuecomment-905532585" title="Approved">MichaelClifford</a>*, *<a href="https://github.com/aicoe-aiops/time-series/pull/46#pullrequestreview-738351629" title="Approved">oindrillac</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aicoe-aiops%2Ftime-series).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/aicoe-aiops/time-series/blob/master/OWNERS)~~ [MichaelClifford]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-08-25 14:08 UTC, merged