[WIP do not merge] Notebook 2
aicoe-aiops/time-series pull request #7
Opened 2020-11-20 21:25 UTC by Shreyanand

In this PR, I add a notebook for data manipulation and visualization addressing #5.

2020-11-20 21:41 UTC, sesheta commented
<details>
<summary>Pre-Commit Test failed! Click here</summary>

```
[INFO] Initializing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pycqa/pydocstyle.git.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/tomcatling/black-nb.
[INFO] Initializing environment for https://github.com/s-weigand/flake8-nb.
[INFO] Initializing environment for https://github.com/s-weigand/flake8-nb:pep8-naming.
[INFO] Installing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pycqa/pydocstyle.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/tomcatling/black-nb.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/s-weigand/flake8-nb.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Tabs remover.............................................................Passed
Trim Trailing Whitespace.................................................Passed
Check for merge conflicts................................................Passed
Fix End of Files.........................................................Passed
Tests should end in _test.py.........................(no files to check)Skipped
Check for added large files..............................................Passed
check BOM - deprecated: use fix-byte-order-marker........................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check JSON...............................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Detect Private Key.......................................................Passed
Check python ast.........................................................Passed
Debug Statements (Python)................................................Passed
pydocstyle...............................................................Passed
Check Toml...............................................................Passed
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
mypy.....................................................................Passed
black....................................................................Passed
black-nb.................................................................Failed
- hook id: black-nb
- files were modified by this hook

reformatted notebooks/ts-2-visualization.ipynb
    13 cells reformatted, 5 cells left unchanged.
All done!
1 file reformatted.

flake8-nb................................................................Failed
- hook id: flake8-nb
- exit code: 1

notebooks/ts-2-visualization.ipynb#In[2]:1:1: E402 module level import not at top of file
notebooks/ts-2-visualization.ipynb#In[2]:2:1: E402 module level import not at top of file
notebooks/ts-2-visualization.ipynb#In[2]:3:1: E402 module level import not at top of file
notebooks/ts-2-visualization.ipynb#In[2]:4:1: E402 module level import not at top of file
notebooks/ts-2-visualization.ipynb#In[2]:5:1: E402 module level import not at top of file
notebooks/ts-2-visualization.ipynb#In[2]:6:1: E402 module level import not at top of file
notebooks/ts-2-visualization.ipynb#In[2]:7:1: E402 module level import not at top of file
notebooks/ts-2-visualization.ipynb#In[2]:7:1: F401 'os' imported but unused
notebooks/ts-2-visualization.ipynb#In[2]:8:1: E402 module level import not at top of file
notebooks/ts-2-visualization.ipynb#In[170]:2:2: N816 variable 'ts_D' in global scope should not be mixedCase
notebooks/ts-2-visualization.ipynb#In[171]:2:2: N816 variable 'ts_H' in global scope should not be mixedCase
notebooks/ts-2-visualization.ipynb#In[173]:2:2: N816 variable 'ts_UH' in global scope should not be mixedCase
```
</details>

2020-11-20 21:43 UTC, sesheta commented
<details>
<summary>Pre-Commit Test failed! Click here</summary>

```
[INFO] Initializing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pycqa/pydocstyle.git.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/tomcatling/black-nb.
[INFO] Initializing environment for https://github.com/s-weigand/flake8-nb.
[INFO] Initializing environment for https://github.com/s-weigand/flake8-nb:pep8-naming.
[INFO] Installing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pycqa/pydocstyle.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/tomcatling/black-nb.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/s-weigand/flake8-nb.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Tabs remover.............................................................Passed
Trim Trailing Whitespace.................................................Passed
Check for merge conflicts................................................Passed
Fix End of Files.........................................................Passed
Tests should end in _test.py.........................(no files to check)Skipped
Check for added large files..............................................Passed
check BOM - deprecated: use fix-byte-order-marker........................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check JSON...............................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Detect Private Key.......................................................Passed
Check python ast.........................................................Passed
Debug Statements (Python)................................................Passed
pydocstyle...............................................................Passed
Check Toml...............................................................Passed
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
mypy.....................................................................Passed
black....................................................................Passed
black-nb.................................................................Failed
- hook id: black-nb
- files were modified by this hook

reformatted notebooks/ts-2-visualization.ipynb
    13 cells reformatted, 5 cells left unchanged.
All done!
1 file reformatted.

flake8-nb................................................................Failed
- hook id: flake8-nb
- exit code: 1

notebooks/ts-2-visualization.ipynb#In[2]:1:1: E402 module level import not at top of file
notebooks/ts-2-visualization.ipynb#In[2]:2:1: E402 module level import not at top of file
notebooks/ts-2-visualization.ipynb#In[2]:3:1: E402 module level import not at top of file
notebooks/ts-2-visualization.ipynb#In[2]:4:1: E402 module level import not at top of file
notebooks/ts-2-visualization.ipynb#In[2]:5:1: E402 module level import not at top of file
notebooks/ts-2-visualization.ipynb#In[2]:6:1: E402 module level import not at top of file
notebooks/ts-2-visualization.ipynb#In[2]:7:1: E402 module level import not at top of file
notebooks/ts-2-visualization.ipynb#In[2]:7:1: F401 'os' imported but unused
notebooks/ts-2-visualization.ipynb#In[2]:8:1: E402 module level import not at top of file
notebooks/ts-2-visualization.ipynb#In[170]:2:2: N816 variable 'ts_D' in global scope should not be mixedCase
notebooks/ts-2-visualization.ipynb#In[171]:2:2: N816 variable 'ts_H' in global scope should not be mixedCase
notebooks/ts-2-visualization.ipynb#In[173]:2:2: N816 variable 'ts_UH' in global scope should not be mixedCase
```
</details>

2020-11-24 10:49 UTC, tumido commented
/retest

2020-12-01 19:30 UTC, sesheta commented
<details>
<summary>Pre-Commit Test failed! Click here</summary>

```
[INFO] Initializing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pycqa/pydocstyle.git.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/tomcatling/black-nb.
[INFO] Initializing environment for https://github.com/s-weigand/flake8-nb.
[INFO] Initializing environment for https://github.com/s-weigand/flake8-nb:pep8-naming.
[INFO] Installing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pycqa/pydocstyle.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/tomcatling/black-nb.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/s-weigand/flake8-nb.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Tabs remover.............................................................Passed
Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing requirements.txt

Check for merge conflicts................................................Passed
Fix End of Files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing requirements.txt

Tests should end in _test.py.........................(no files to check)Skipped
Check for added large files..............................................Passed
check BOM - deprecated: use fix-byte-order-marker........................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check JSON...............................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Detect Private Key.......................................................Passed
Check python ast.........................................................Passed
Debug Statements (Python)................................................Passed
pydocstyle...............................................................Passed
Check Toml...............................................................Passed
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
mypy.....................................................................Passed
black....................................................................Passed
black-nb.................................................................Failed
- hook id: black-nb
- files were modified by this hook

reformatted notebooks/ts-2-visualization.ipynb
    2 cells reformatted, 15 cells left unchanged.
All done!
1 file reformatted.

flake8-nb................................................................Passed
```
</details>

2020-12-01 19:44 UTC, 4n4nd requested changes
1 minor spelling error, otherwise LGTM :+1:

2020-12-01 22:18 UTC, Shreyanand commented
> 1 minor spelling error, otherwise LGTM

Fixed.

2020-12-02 09:38 UTC, tumido commented on requirements.txt
> +prometheus-api-client
@Shreyanand not sure, if I missed the reason to include `requirements.txt` in here but I'd suggest you to include only either `Pipfile.*` or `requrements.txt` (I would favor Pipfile), the other one is redundant.

2020-12-02 16:39 UTC, MichaelClifford approved these changes
LGTM

2020-12-08 00:09 UTC, Shreyanand commented on requirements.txt
> +prometheus-api-client
Removed requrements.txt

2020-12-08 17:54 UTC, tumido approved these changes

2020-12-08 17:55 UTC, merged